version: '3'

tasks:
  shell:
    desc: start a devbox shell in current dir
    cmds:
      - devbox shell
  kw:
    desc: start keywordspark devbox
    dir: ~/github-personal/keywordspark/
    cmds:
      - devbox run
      
